### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DegenRisk** [gianlucamalato/machinelearning#1]
Hi, is there any chance you may be able to help me figure out how I might be able to make pivot points and support and resistance lines for a monthly time frame, which fills every row for the month so say the pivot is 1.22 for the month, how could it say this in the 30 or 31 rows of the monthly pivot column to match the daily time series? I would really appreciate it if you have an idea

**Comment by gianlucamalato** [comment]
Sorry, I don't understand your question.

**Comment by DegenRisk** [comment]
I am trying to create feautures to feed a neural network, in designated
columns I am looking to have the monthly pivot, weekly pivot and daily
pivots as well as support and resistance, I think it can be done with
pandas.fill so

**Comment by gianlucamalato** [comment]
You can calculate pivot points with different periods changing the period in the yahoo finance function for downloading data, for example.
